### ISSUE TITLE
Missing 1 required positional argument: 'data'

### ISSUE THREAD

**Issue by Kif11** [peopledoc/swagman#6]
Getting this error

```
$: swagman ./postman.json
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/swagman", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/swagman.py", line 880, in main
    environment = CollectionContext.from_file(args.environment)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/swagman.py", line 68, in from_file
    return cls()
TypeError: __init__() missing 1 required positional argument: 'data'
```

**Comment by b3ll0v1c** [comment]
@Kif11 Did you get it to work? I am getting a similar error.

**Comment by Kif11** [comment]
@b3ll0v1c No, I didn't solve it. I think, I used online converter instead.

**Comment by SturatParker** [comment]
Same issue using Win10 Python3.7

**Comment by memory-yancy** [comment]
Maybe it's useful to read `README.md` carefully, note input file should be `a collection report`, or it can not find any `run, executions` etc. items
> Convert PostMan Collection Report to Swagger file.
> See: https://github.com/postmanlabs/newman#json-reporter-options

About error, since `args.environment` value default is None when someone do not assign it, therefore:
```
diff --git a/swagman.py b/swagman.py
index f6d4db4..08d640f 100644
--- a/swagman.py
+++ b/swagman.py
@@ -47,7 +47,7 @@ class CollectionTemplate(Template):

 class CollectionContext(dict):

-    def __init__(self, data):
+    def __init__(self, data={}):
         for item in (data.get('values') or []):
             if not item.get('enabled'):
                 continue
```

**Comment by henrygreenQuinnox** [comment]
Is there any workaround for this? I have tried passing the Newman output into Swagman and am getting the same error
